name: Deploy Static HTML to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'devops-mo'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3108463920268F31 }}
